### ISSUE TITLE
Fix the import statement and dependencies

### ISSUE THREAD

**Issue by Ashish-Ban** [DIGIEGGS/rn-country-code-picker#14]
Error: Unable to resolve module rn-country-code-picker, rn-country-code-picker could not be found within the project.

I had this problem with importing the library, To fix this problem change the import from 

```js
import { CallingCodePicker } from 'rn-country-code-picker';
```
to :
```js
import { CallingCodePicker } from '@digieggs/rn-country-code-picker';
```

**Comment by Ashish-Ban** [comment]
[Fri Mar 12 2021 20:58:15.308]  ERROR    Error: react-native-localize: NativeModule.RNLocalize is null. To fix this issue try these steps:
• Run `react-native link react-native-localize` in the project root.
• Rebuild and re-run the app.
• If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get 
the new pods.
• Check that the library was linked correctly when you used the link command by running through the manual installation instructions in the README.
• If you are getting this error while unit testing you need to mock the native module. Follow the guide in the README.
• If none of these fix the issue, please open an issue on the Github repository: https://github.com/zoontek/react-native-localize
[Fri Mar 12 2021 20:58:15.310]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Fri Mar 12 2021 20:58:15.311]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

Currently Having Trouble with this problem. I installed the react-native-localize library. Installing the react-native-localize library and rebuilding the app fixes this

## Hope this helps others who have the same issue.

**Comment by Ashish-Ban** [comment]
## Fixing all the dependency errors and then rebuilding the app does work but when you open or go to the component where you use the country code picker app gets stuck at that screen.

The probable cause it the infinite state checking in the onValueChange method of this library. If you add a console log to that method it triggers infinitely when the app starts ... or sometimes even the app does not even render any screen or component.

**Comment by Anzormumladze** [comment]
> ## Fixing all the dependency errors and then rebuilding the app does work but when you open or go to the component where you use the country code picker app gets stuck at that screen.
> The probable cause it the infinite state checking in the onValueChange method of this library. If you add a console log to that method it triggers infinitely when the app starts ... or sometimes even the app does not even render any screen or component.

I'm having the same issue, can you remember how you fixed it?
