### ISSUE TITLE
This library is not working on android

### ISSUE THREAD

**Issue by adam-risberg** [DIGIEGGS/rn-country-code-picker#19]
This library renders the list of countries using absolute positioning to overflow the parent button component. On Android, children overflowing their parent are not able to receive input events such as pressing and dragging, which renders this library useless on Android.

**Comment by loneddonkey** [comment]
Hello,
Necessary fixes applied, merged into main branch and published to npm. 

Thank you for installing the package and opening this issue.

**Comment by loneddonkey** [comment]
Hello,
Necessary fixes applied, merged into main branch and published to npm. 

Thank you for installing the package and opening this issue.
