### ISSUE TITLE
Hide country flag

### ISSUE THREAD

**Issue by julekgwa** [DIGIEGGS/rn-country-code-picker#31]
Hi guys. Apologies for posting this as an issue.  Is it possible to hide the country flag and only display the calling code?

**Comment by isatanis** [comment]
Hey @julekgwa. I think this is a good feature. we'll add this to our release calendar. Thanks for sharing. 👍

**Comment by loneddonkey** [comment]
Hey @julekgwa 
You can now use [`isFlagVisible`](https://github.com/DIGIEGGS/rn-country-code-picker/tree/v1.4.0#isFlagVisible) prop to hide or show the flag with [v1.4.0](https://github.com/DIGIEGGS/rn-country-code-picker/releases/tag/v1.4.0).
Thank you for opening this issue.
